#include<iostream>
#include <vector>
using namespace std;

/*
    First 'for' generate 2^n - 1 number.
    Second 'for' reads bit by bit each number generated by first 'for'.
    The clause 'if' verify weather the bit is turn on.
        i=1   |  j < 3       
        001   & 001  = true
        001   & 010  = false 
        001   & 100  = false

*/

void bitMask(vector<string> &v){
    int _n = v.size();
    for(int i=0; i<(1<<_n); i++){
        string s = "";
        for(int j = 0; j<_n; j++){        
            if(i&(1<<j)){
                s += " "+v[j];
            }
                    
        }
        cout<<s;
        cout<<endl;
    }
}

int main(int argc, char const *argv[])
{
    vector<string> v;
    v.push_back("1");
    v.push_back("2");
    v.push_back("3");
    v.push_back("4");
    v.push_back("5");
    bitMask(v);

    return 0;
}
